# Generated by Django 4.2.24 on 2025-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_workspace_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member'), ('GUEST', 'Guest')], default='OWNER', max_length=10),
        ),
    ]
